from lcb_runner.prompts.code_execution import format_prompt_execution, format_prompt_execution_cot
from lcb_runner.prompts.code_generation import format_prompt_generation
from lcb_runner.prompts.test_output_prediction import format_prompt_test_output
from lcb_runner.prompts.self_repair import format_prompt_self_repair
from lcb_runner.prompts.test_case_generation import format_prompt_testcase_generate
from lcb_runner.prompts.checker_extend import format_prompt_checker_extend
from lcb_runner.prompts.test_inputer_generation import format_prompt_inputer_generate